blank_issues_enabled: false
contact_links:
  - name: SpigotMC Resource Page
    url: https://www.spigotmc.org/resources/110741
    about: View the plugin on SpigotMC, read reviews, and ask general questions
  - name: Documentation
    url: https://github.com/H7KZ/Disenchantment/blob/master/README.md
    about: Read the full documentation including commands, configuration, and FAQ
